<img src= "https://taampasteel.com/wp-content/uploads/2018/01/Steel-Facts.jpg" width="400" height="400">

In [1]:
############!Imports!###########
import pandas as pd
import matplotlib.pyplot as plt
import statistics as st
import numpy as np
import math

steel_df = pd.read_csv('steel_strength.csv')
steel_df

,formula,c,mn,si,cr,ni,mo,v,n,nb,co,w,al,ti,yield strength,tensile strength,elongation
0,Fe0.620C0.000953Mn0.000521Si0.00102Cr0.000110N...,0.02,0.05,0.05,0.01,19.70,2.95,0.01,0.00,0.01,15.00,0.00,0.15,1.55,2411.5,2473.5,7.0
1,Fe0.623C0.00854Mn0.000104Si0.000203Cr0.147Ni0....,0.18,0.01,0.01,13.44,0.01,3.01,0.46,0.04,0.01,19.46,2.35,0.04,0.00,1123.1,1929.2,8.0
2,Fe0.625Mn0.000102Si0.000200Cr0.0936Ni0.129Mo0....,0.00,0.01,0.01,8.67,13.45,0.82,0.01,0.00,0.01,13.90,0.00,0.39,0.57,1736.3,1871.8,NaN
3,Fe0.634C0.000478Mn0.000523Si0.00102Cr0.000111N...,0.01,0.05,0.05,0.01,17.70,3.95,0.01,0.00,0.01,15.00,0.00,0.13,1.47,2487.3,2514.9,9.0
4,Fe0.636C0.000474Mn0.000518Si0.00101Cr0.000109N...,0.01,0.05,0.05,0.01,19.40,1.45,0.01,0.00,0.01,14.90,0.00,0.13,1.55,2249.6,2315.0,8.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,Fe0.823C0.0176Mn0.00183Si0.000198Cr0.0779Ni0.0...,0.38,0.18,0.01,7.27,0.01,3.77,0.96,0.00,0.01,4.90,0.00,0.03,0.00,1722.5,1998.1,5.0
308,Fe0.823Mn0.000618Si0.00101Cr0.0561Ni0.0984Mo0....,0.00,0.06,0.05,5.15,10.20,3.20,0.01,0.00,0.01,0.01,0.00,0.03,0.09,1019.0,1019.0,19.0
309,Fe0.825C0.0174Mn0.00175Si0.000201Cr0.0565Ni0.0...,0.37,0.17,0.01,5.20,0.01,5.84,1.05,0.00,0.91,4.88,0.00,0.03,0.00,1860.3,2156.6,3.0
310,Fe0.858C0.0191Mn0.00194Si0.000199Cr0.0753Ni0.0...,0.41,0.19,0.01,6.99,0.01,5.84,0.92,0.00,0.01,0.02,0.00,0.03,0.00,1812.1,2087.7,2.0
311,Fe0.860C0.0125Mn0.00274Si0.000198Cr0.00439Ni0....,0.27,0.27,0.01,0.41,8.28,0.49,0.07,0.00,0.01,3.90,0.00,0.03,0.00,1139.7,1236.3,15.4

In [2]:
steel_df = steel_df.drop('formula', axis=1)
steel_df_elements = steel_df.drop('yield strength', axis=1).drop('elongation', axis=1)

In [3]:
steel_df_elements

,c,mn,si,cr,ni,mo,v,n,nb,co,w,al,ti,tensile strength
0,0.02,0.05,0.05,0.01,19.70,2.95,0.01,0.00,0.01,15.00,0.00,0.15,1.55,2473.5
1,0.18,0.01,0.01,13.44,0.01,3.01,0.46,0.04,0.01,19.46,2.35,0.04,0.00,1929.2
2,0.00,0.01,0.01,8.67,13.45,0.82,0.01,0.00,0.01,13.90,0.00,0.39,0.57,1871.8
3,0.01,0.05,0.05,0.01,17.70,3.95,0.01,0.00,0.01,15.00,0.00,0.13,1.47,2514.9
4,0.01,0.05,0.05,0.01,19.40,1.45,0.01,0.00,0.01,14.90,0.00,0.13,1.55,2315.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,0.38,0.18,0.01,7.27,0.01,3.77,0.96,0.00,0.01,4.90,0.00,0.03,0.00,1998.1
308,0.00,0.06,0.05,5.15,10.20,3.20,0.01,0.00,0.01,0.01,0.00,0.03,0.09,1019.0
309,0.37,0.17,0.01,5.20,0.01,5.84,1.05,0.00,0.91,4.88,0.00,0.03,0.00,2156.6
310,0.41,0.19,0.01,6.99,0.01,5.84,0.92,0.00,0.01,0.02,0.00,0.03,0.00,2087.7
311,0.27,0.27,0.01,0.41,8.28,0.49,0.07,0.00,0.01,3.90,0.00,0.03,0.00,1236.3

In [4]:
#Conferindo quÃ£o presente estÃ¡ em cada
for collumn in steel_df_elements:
    conj = 0
    for value in steel_df_elements[collumn]:
        if value != 0:
            conj = conj+1
    print(collumn)
    print(conj)

c
286
mn
312
si
312
cr
312
ni
312
mo
312
v
310
n
43
nb
310
co
312
w
16
al
312
ti
195
tensile strength
312

In [5]:
#Retirando as linhas que contÃ©m tungstÃªnio (w)
steel_df_elements = steel_df_elements[steel_df_elements["w"] == 0]

#Retirando a coluna "w"
steel_df_elements = steel_df_elements.drop("w", axis = 1)

In [6]:
#Adicionando Ferro

elementos = ["c", "mn", "si", "cr", "ni", "mo", "v", "n", "nb", "co", "al", "ti"]
fe = 100 - steel_df_elements[elementos].sum(axis = 1)
steel_df_elements["fe"] = fe
steel_df_elements

,c,mn,si,cr,ni,mo,v,n,nb,co,al,ti,tensile strength,fe
0,0.02,0.05,0.05,0.01,19.70,2.95,0.01,0.0,0.01,15.00,0.15,1.55,2473.5,60.50
2,0.00,0.01,0.01,8.67,13.45,0.82,0.01,0.0,0.01,13.90,0.39,0.57,1871.8,62.16
3,0.01,0.05,0.05,0.01,17.70,3.95,0.01,0.0,0.01,15.00,0.13,1.47,2514.9,61.61
4,0.01,0.05,0.05,0.01,19.40,1.45,0.01,0.0,0.01,14.90,0.13,1.55,2315.0,62.43
5,0.19,0.02,0.49,12.56,0.94,1.96,0.01,0.0,0.01,20.10,0.03,0.00,1779.5,63.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307,0.38,0.18,0.01,7.27,0.01,3.77,0.96,0.0,0.01,4.90,0.03,0.00,1998.1,82.48
308,0.00,0.06,0.05,5.15,10.20,3.20,0.01,0.0,0.01,0.01,0.03,0.09,1019.0,81.19
309,0.37,0.17,0.01,5.20,0.01,5.84,1.05,0.0,0.91,4.88,0.03,0.00,2156.6,81.53
310,0.41,0.19,0.01,6.99,0.01,5.84,0.92,0.0,0.01,0.02,0.03,0.00,2087.7,85.57
311,0.27,0.27,0.01,0.41,8.28,0.49,0.07,0.0,0.01,3.90,0.03,0.00,1236.3,86.26

In [7]:
#Normalizando concentraÃ§Ãµes por mÃ¡ximo

In [8]:
#Transformando 0 em NaN
logic = steel_df_elements == 0
steel_df_elements[logic] = pd.NA
#steel_df_elements

In [9]:
#Verificando a correlaÃ§Ã£o dos materiais e ResistÃªncia Ã  traÃ§Ã£o mÃ¡xima
matrix_corr = steel_df_elements.corr()
matrix_corr = matrix_corr.loc['tensile strength']
matrix_corr = matrix_corr.drop('tensile strength')
matrix_corr

c     0.511959
mn   -0.133050
si   -0.065820
cr   -0.084501
ni   -0.196044
mo    0.226035
v     0.241458
n     0.206366
nb    0.051821
co    0.548990
al   -0.282354
ti    0.522849
fe   -0.431344
Name: tensile strength, dtype: float64